apiVersion: v1
kind: Service
metadata:
  name: tablegpt-meter
  labels:
    app: tablegpt-meter
spec:
  ports:
    - name: http-port
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc-port
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: tablegpt-meter
