apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/name: redis
      app.kubernetes.io/version: '7'
      app.kubernetes.io/managed-by: kubectl
    includeSelectors: false

resources:
  - deployment.yaml
  - service.yaml
